// =================================================================
// --- SUPPLEMENTS DATABASE (57 ITEMS - V4.2.3 - BILINGUAL - RESEARCHED) ---
// =================================================================

const supplements = [
    // --- KATEGORIE: SÍLA (STRENGTH) ---
    { 
        id: 1, 
        category: "Síla", 
        confidence: "high", 
        link: "https://examine.com/supplements/creatine/", 
        icon: "⚡", 
        contains: ["Kreatin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/12701815/", "https://jissn.biomedcentral.com/articles/10.1186/s12970-017-0173-z"],
        synergy: ["Sacharidy", "Voda", "Beta-Alanin"], 
        conflict: [], 
        name: { cs: "Kreatin Monohydrát", en: "Creatine Monohydrate" },
        description: { cs: "Zvyšuje zásoby ATP. Nejvíce prozkoumaný doplněk pro sílu.", en: "Increases ATP stores. Most researched supplement for strength." },
        benefits: { cs: ["Zvyšuje sílu", "Svalový objem", "Výbušnost"], en: ["Increases strength", "Muscle volume", "Explosive power"] }, 
        dosage: "5g", 
        timing: { cs: "Kdykoliv (ideálně po tréninku)", en: "Anytime (ideally post-workout)" }
    },
    { 
        id: 2, 
        category: "Síla", 
        confidence: "high", 
        link: "https://examine.com/supplements/whey-protein/", 
        icon: "🥛", 
        contains: ["Bílkoviny"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/24015719/", "https://pubmed.ncbi.nlm.nih.gov/22150425/"],
        synergy: ["Kreatin", "Sacharidy"], 
        conflict: [], 
        name: { cs: "Syrovátkový Protein", en: "Whey Protein" },
        description: { cs: "Rychle stravitelná bílkovina s vysokou biologickou hodnotou.", en: "Fast-digesting protein with high biological value." },
        benefits: { cs: ["Rychlá regenerace", "Růst svalů"], en: ["Fast recovery", "Muscle growth"] }, 
        dosage: "20-40g", 
        timing: { cs: "Po tréninku / Svačina", en: "Post-workout / Snack" }
    },
    { 
        id: 3, 
        category: "Síla", 
        confidence: "high", 
        link: "https://examine.com/supplements/casein-protein/", 
        icon: "🌙", 
        contains: ["Bílkoviny"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22330017/", "https://pubmed.ncbi.nlm.nih.gov/11158517/"],
        synergy: ["Probiotika"], 
        conflict: [], 
        name: { cs: "Kasein (Micelární)", en: "Casein (Micellar)" },
        description: { cs: "Pomalý protein, uvolňuje aminokyseliny až 7 hodin.", en: "Slow-digesting protein, releases amino acids for up to 7 hours." },
        benefits: { cs: ["Noční regenerace", "Antikatabolický"], en: ["Night recovery", "Anti-catabolic"] }, 
        dosage: "30g", 
        timing: { cs: "Před spaním", en: "Before bed" }
    },
    { 
        id: 4, 
        category: "Síla", 
        confidence: "high", 
        link: "https://examine.com/supplements/citrulline/", 
        icon: "🍉", 
        contains: ["Citrulin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/20499249/", "https://pubmed.ncbi.nlm.nih.gov/20386132/"],
        synergy: ["Sůl", "Arginin"], 
        conflict: [], 
        name: { cs: "L-Citrulin Malát", en: "L-Citrulline Malate" },
        description: { cs: "Zvyšuje oxid dusnatý (NO) a průtok krve svaly. Účinnější než Arginin.", en: "Increases nitric oxide (NO) and blood flow. More effective than Arginine." },
        benefits: { cs: ["Svalová pumpa", "Oddálení únavy"], en: ["Muscle pump", "Delayed fatigue"] }, 
        dosage: "6-8g", 
        timing: { cs: "Před tréninkem", en: "Pre-workout" }
    },
    { 
        id: 5, 
        category: "Síla", 
        confidence: "high", 
        link: "https://examine.com/supplements/beta-alanine/", 
        icon: "🐜", 
        contains: ["Beta-Alanin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22270434/", "https://pubmed.ncbi.nlm.nih.gov/17194255/"],
        synergy: ["Kreatin"], 
        conflict: [], 
        name: { cs: "Beta-Alanin", en: "Beta-Alanine" },
        description: { cs: "Zvyšuje hladinu karnosinu, snižuje zakyselení.", en: "Increases carnosine levels, buffers acidity." },
        benefits: { cs: ["Svalová vytrvalost", "Výkon v sériích 60s+"], en: ["Muscular endurance", "Performance in 60s+ sets"] }, 
        dosage: "3-5g", 
        timing: { cs: "Před tréninkem", en: "Pre-workout" }
    },
    { 
        id: 6, 
        category: "Síla", 
        confidence: "medium", 
        link: "https://examine.com/supplements/bcaa/", 
        icon: "🧬", 
        contains: ["Aminokyseliny"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/21297567/", "https://pubmed.ncbi.nlm.nih.gov/20300014/"],
        synergy: ["Elektrolyty"], 
        conflict: [], 
        name: { cs: "EAA (Esenciální AK)", en: "EAA (Essential AA)" },
        description: { cs: "Komplex 9 esenciálních aminokyselin pro ochranu svalů.", en: "Complex of 9 essential amino acids for muscle protection." },
        benefits: { cs: ["Ochrana svalů", "Regenerace"], en: ["Muscle protection", "Recovery"] }, 
        dosage: "10-15g", 
        timing: { cs: "Během tréninku", en: "Intra-workout" }
    },
    { 
        id: 7, 
        category: "Síla", 
        confidence: "medium", 
        link: "https://examine.com/supplements/hmb/", 
        icon: "🛑", 
        contains: ["HMB"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/24294435/", "https://pubmed.ncbi.nlm.nih.gov/11726472/"],
        synergy: ["Kreatin"], 
        conflict: [], 
        name: { cs: "HMB", en: "HMB" },
        description: { cs: "Metabolit leucinu. Pomáhá proti rozpadu svalů.", en: "Leucine metabolite. Helps prevent muscle breakdown." },
        benefits: { cs: ["Antikatabolický efekt", "Regenerace"], en: ["Anti-catabolic effect", "Recovery"] }, 
        dosage: "3g", 
        timing: { cs: "Před tréninkem", en: "Pre-workout" }
    },
    { 
        id: 8, 
        category: "Síla", 
        confidence: "medium", 
        link: "https://examine.com/supplements/betaine/", 
        icon: "🚀", 
        contains: ["Betain"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/23967897/", "https://pubmed.ncbi.nlm.nih.gov/19250534/"],
        synergy: ["Kreatin"], 
        conflict: [], 
        name: { cs: "Betain", en: "Betaine" },
        description: { cs: "Osmolyt podporující hydrataci buněk a výbušnost.", en: "Osmolyte supporting cell hydration and explosive power." },
        benefits: { cs: ["Výbušná síla", "Proteosyntéza"], en: ["Explosive power", "Protein synthesis"] }, 
        dosage: "2.5g", 
        timing: { cs: "Před tréninkem", en: "Pre-workout" }
    },
    { 
        id: 9, 
        category: "Síla", 
        confidence: "medium", 
        link: "https://examine.com/supplements/taurine/", 
        icon: "🐂", 
        contains: ["Taurin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/24383513/", "https://pubmed.ncbi.nlm.nih.gov/22855206/"],
        synergy: ["Elektrolyty"], 
        conflict: [], 
        name: { cs: "Taurin", en: "Taurine" },
        description: { cs: "Aminokyselina pro hydrataci buněk a funkci nervů.", en: "Amino acid for cell hydration and nerve function." },
        benefits: { cs: ["Prevence křečí", "Srdeční zdraví"], en: ["Cramp prevention", "Heart health"] }, 
        dosage: "1-2g", 
        timing: { cs: "Před tréninkem", en: "Pre-workout" }
    },
    { 
        id: 10, 
        category: "Síla", 
        confidence: "high", 
        link: "https://pubmed.ncbi.nlm.nih.gov/30043889/", 
        icon: "💧", 
        contains: ["Sodík", "Draslík", "Hořčík"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/30043889/", "https://pubmed.ncbi.nlm.nih.gov/17277604/"],
        synergy: ["Voda", "Sacharidy"], 
        conflict: [], 
        name: { cs: "Elektrolyty", en: "Electrolytes" },
        description: { cs: "Minerály ztracené potem. Kritické pro výkon.", en: "Minerals lost via sweat. Critical for performance." },
        benefits: { cs: ["Hydratace", "Výkon", "Proti křečím"], en: ["Hydration", "Performance", "Anti-cramp"] }, 
        dosage: "Dle potřeby", 
        timing: { cs: "Během tréninku", en: "Intra-workout" }
    },
    { 
        id: 11, 
        category: "Síla", 
        confidence: "medium", 
        link: "https://examine.com/supplements/arginine/", 
        icon: "🩸", 
        contains: ["Arginin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/17143054/", "https://pubmed.ncbi.nlm.nih.gov/19076168/"],
        synergy: ["Citrulin"], 
        conflict: [], 
        name: { cs: "Arginin A-KG", en: "Arginine A-KG" },
        description: { cs: "Prekurzor NO pro krátkodobé prokrvení.", en: "NO precursor for short-term blood flow." },
        benefits: { cs: ["Krátkodobá pumpa"], en: ["Short-term pump"] }, 
        dosage: "3-5g", 
        timing: { cs: "Před tréninkem", en: "Pre-workout" }
    },
    { 
        id: 12, 
        category: "Síla", 
        confidence: "high", 
        link: "https://examine.com/supplements/carbohydrates/", 
        icon: "🍬", 
        contains: ["Sacharidy"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/15212750/", "https://pubmed.ncbi.nlm.nih.gov/21407127/"],
        synergy: ["Protein", "Kreatin"], 
        conflict: ["Vláknina"], 
        name: { cs: "Maltodextrin / Cluster Dextrin", en: "Maltodextrin / Cluster Dextrin" },
        description: { cs: "Rychlé sacharidy pro doplnění glykogenu.", en: "Fast carbohydrates for glycogen replenishment." },
        benefits: { cs: ["Okamžitá energie", "Regenerace"], en: ["Instant energy", "Recovery"] }, 
        dosage: "30-50g", 
        timing: { cs: "Po tréninku / Při výkonu", en: "Post-workout / Intra-workout" }
    },

    // --- KATEGORIE: ENERGIE & NOOTROPIKA ---
    { 
        id: 13, 
        category: "Energie", 
        confidence: "high", 
        link: "https://examine.com/supplements/caffeine/", 
        icon: "☕", 
        contains: ["Kofein"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/19088583/", "https://pubmed.ncbi.nlm.nih.gov/20205959/"],
        synergy: ["L-Theanin"], 
        conflict: ["Melatonin", "GABA"], 
        name: { cs: "Kofein Anhydrous", en: "Caffeine Anhydrous" },
        description: { cs: "Nejúčinnější stimulant CNS. Zvyšuje bdělost.", en: "Most effective CNS stimulant. Increases alertness." },
        benefits: { cs: ["Bdělost", "Soustředění", "Výkon"], en: ["Alertness", "Focus", "Performance"] }, 
        dosage: "3-6 mg/kg", 
        timing: { cs: "Před tréninkem", en: "Pre-workout" }
    },
    { 
        id: 14, 
        category: "Energie", 
        confidence: "high", 
        link: "https://examine.com/supplements/theanine/", 
        icon: "🧘", 
        contains: ["Theanin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/18296328/", "https://pubmed.ncbi.nlm.nih.gov/21040626/"],
        synergy: ["Kofein"], 
        conflict: [], 
        name: { cs: "L-Theanin", en: "L-Theanine" },
        description: { cs: "Zklidňuje mysl, tlumí nervozitu z kofeinu.", en: "Calms the mind, reduces caffeine jitters." },
        benefits: { cs: ["Klidný focus", "Relaxace"], en: ["Calm focus", "Relaxation"] }, 
        dosage: "100-200mg", 
        timing: { cs: "S kofeinem", en: "With caffeine" }
    },
    { 
        id: 15, 
        category: "Energie", 
        confidence: "high", 
        link: "https://examine.com/supplements/l-tyrosine/", 
        icon: "🧠", 
        contains: ["Tyrosin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/25598314/", "https://pubmed.ncbi.nlm.nih.gov/2735164/"],
        synergy: ["Kofein"], 
        conflict: [], 
        name: { cs: "L-Tyrosin", en: "L-Tyrosine" },
        description: { cs: "Prekurzor dopaminu. Podporuje kognici ve stresu.", en: "Dopamine precursor. Supports cognition under stress." },
        benefits: { cs: ["Focus ve stresu", "Nálada"], en: ["Focus under stress", "Mood"] }, 
        dosage: "1-2g", 
        timing: { cs: "Před tréninkem / Ráno", en: "Pre-workout / Morning" }
    },
    { 
        id: 16, 
        category: "Nootropika", 
        confidence: "medium", 
        link: "https://examine.com/supplements/alpha-gpc/", 
        icon: "💡", 
        contains: ["Cholin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22071706/", "https://pubmed.ncbi.nlm.nih.gov/26512095/"],
        synergy: ["Huperzine A"], 
        conflict: [], 
        name: { cs: "Alpha GPC", en: "Alpha GPC" },
        description: { cs: "Zdroj cholinu pro mozek. Zlepšuje paměť a sílu.", en: "Choline source for the brain. Improves memory and strength." },
        benefits: { cs: ["Paměť", "Učení", "Síla"], en: ["Memory", "Learning", "Strength"] }, 
        dosage: "300-600mg", 
        timing: { cs: "Před prací / tréninkem", en: "Pre-work / Pre-workout" }
    },
    { 
        id: 17, 
        category: "Nootropika", 
        confidence: "medium", 
        link: "https://examine.com/supplements/yamabushitake/", 
        icon: "🍄", 
        contains: ["Lion's Mane"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/18844328/", "https://pubmed.ncbi.nlm.nih.gov/24266378/"],
        synergy: ["Káva"], 
        conflict: [], 
        name: { cs: "Lví hříva (Lion's Mane)", en: "Lion's Mane" },
        description: { cs: "Podporuje růst neuronů (NGF).", en: "Supports neuron growth (NGF)." },
        benefits: { cs: ["Paměť", "Nervy"], en: ["Memory", "Nerves"] }, 
        dosage: "1g", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 18, 
        category: "Energie", 
        confidence: "medium", 
        link: "https://examine.com/supplements/rhodiola-rosea/", 
        icon: "🌺", 
        contains: ["Rhodiola"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/21036578/", "https://pubmed.ncbi.nlm.nih.gov/22228617/"],
        synergy: ["Ashwagandha"], 
        conflict: [], 
        name: { cs: "Rhodiola Rosea", en: "Rhodiola Rosea" },
        description: { cs: "Adaptogen proti únavě a vyhoření.", en: "Adaptogen against fatigue and burnout." },
        benefits: { cs: ["Mentální energie", "Proti stresu"], en: ["Mental energy", "Anti-stress"] }, 
        dosage: "300-500mg", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 19, 
        category: "Energie", 
        confidence: "high", 
        link: "https://examine.com/supplements/yerba-mate/", 
        icon: "🧉", 
        contains: ["Kofein"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22326620/", "https://pubmed.ncbi.nlm.nih.gov/20359265/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Yerba Maté", en: "Yerba Mate" },
        description: { cs: "Přírodní zdroj kofeinu a antioxidantů.", en: "Natural source of caffeine and antioxidants." },
        benefits: { cs: ["Jemná energie", "Trávení"], en: ["Gentle energy", "Digestion"] }, 
        dosage: "Dle chuti", 
        timing: { cs: "Dopoledne", en: "Morning" }
    },
    { 
        id: 20, 
        category: "Energie", 
        confidence: "medium", 
        link: "https://pubmed.ncbi.nlm.nih.gov/29914035/", 
        icon: "🥥", 
        contains: ["MCT"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/29914035/", "https://pubmed.ncbi.nlm.nih.gov/25636220/"],
        synergy: ["Káva"], 
        conflict: ["Vysoké sacharidy"], 
        name: { cs: "MCT Olej (C8)", en: "MCT Oil (C8)" },
        description: { cs: "Rychlá energie pro mozek ve formě ketonů.", en: "Fast brain energy in the form of ketones." },
        benefits: { cs: ["Okamžitá energie", "Hlad"], en: ["Instant energy", "Hunger control"] }, 
        dosage: "10-15ml", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 21, 
        category: "Nootropika", 
        confidence: "medium", 
        link: "https://examine.com/supplements/huperzine-a/", 
        icon: "🌿", 
        contains: ["Huperzine"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/10678121/", "https://pubmed.ncbi.nlm.nih.gov/15956816/"],
        synergy: ["Alpha GPC"], 
        conflict: [], 
        name: { cs: "Huperzine A", en: "Huperzine A" },
        description: { cs: "Inhibitor rozkladu acetylcholinu. Zvyšuje focus.", en: "Acetylcholine breakdown inhibitor. Increases focus." },
        benefits: { cs: ["Focus", "Paměť"], en: ["Focus", "Memory"] }, 
        dosage: "200mcg", 
        timing: { cs: "Ráno (cyklovat!)", en: "Morning (cycle!)" }
    },
    { 
        id: 22, 
        category: "Nootropika", 
        confidence: "medium", 
        link: "https://examine.com/supplements/bacopa-monnieri/", 
        icon: "🌱", 
        contains: ["Bacopa"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/11498727/", "https://pubmed.ncbi.nlm.nih.gov/23788517/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Bacopa Monnieri", en: "Bacopa Monnieri" },
        description: { cs: "Bylina pro dlouhodobé zlepšení paměti.", en: "Herb for long-term memory improvement." },
        benefits: { cs: ["Paměť", "Úzkost"], en: ["Memory", "Anxiety"] }, 
        dosage: "300mg", 
        timing: { cs: "S jídlem", en: "With food" }
    },
    { 
        id: 23, 
        category: "Energie", 
        confidence: "medium", 
        link: "https://examine.com/supplements/panax-ginseng/", 
        icon: "🧧", 
        contains: ["Ginseng"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/12020734/", "https://pubmed.ncbi.nlm.nih.gov/23853335/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Panax Ginseng (Ženšen)", en: "Panax Ginseng" },
        description: { cs: "Tradiční bylina pro vitalitu a energii.", en: "Traditional herb for vitality and energy." },
        benefits: { cs: ["Energie", "Imunita"], en: ["Energy", "Immunity"] }, 
        dosage: "200-400mg", 
        timing: { cs: "Ráno", en: "Morning" }
    },

    // --- KATEGORIE: ZDRAVÍ (HEALTH) ---
    { 
        id: 24, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/magnesium/", 
        icon: "💤", 
        contains: ["Hořčík"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/23853335/", "https://pubmed.ncbi.nlm.nih.gov/28445426/"],
        synergy: ["Zinek", "B6"], 
        conflict: ["Vápník"], 
        name: { cs: "Hořčík Bisglycinát", en: "Magnesium Bisglycinate" },
        description: { cs: "Vysoká vstřebatelnost, nedráždí žaludek. Pro relaxaci.", en: "High absorption, gentle on stomach. For relaxation." },
        benefits: { cs: ["Relaxace", "Spánek", "Nervy"], en: ["Relaxation", "Sleep", "Nerves"] }, 
        dosage: "300-400mg", 
        timing: { cs: "Večer", en: "Evening" }
    },
    { 
        id: 25, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/zinc/", 
        icon: "🛡️", 
        contains: ["Zinek"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22055504/", "https://pubmed.ncbi.nlm.nih.gov/15496046/"],
        synergy: ["Hořčík"], 
        conflict: ["Vápník", "Železo"], 
        name: { cs: "Zinek Bisglycinát", en: "Zinc Bisglycinate" },
        description: { cs: "Klíčový pro imunitu a testosteron.", en: "Key for immunity and testosterone." },
        benefits: { cs: ["Imunita", "Testosteron", "Pleť"], en: ["Immunity", "Testosterone", "Skin"] }, 
        dosage: "15mg", 
        timing: { cs: "Večer s jídlem", en: "Evening with food" }
    },
    { 
        id: 26, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/fish-oil/", 
        icon: "🐟", 
        contains: ["Omega-3"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22332096/", "https://pubmed.ncbi.nlm.nih.gov/11997392/"],
        synergy: ["Vitamín D3"], 
        conflict: [], 
        name: { cs: "Omega-3 (EPA/DHA)", en: "Omega-3 (EPA/DHA)" },
        description: { cs: "Esenciální mastné kyseliny. Protizánětlivé.", en: "Essential fatty acids. Anti-inflammatory." },
        benefits: { cs: ["Srdce", "Mozek", "Klouby"], en: ["Heart", "Brain", "Joints"] }, 
        dosage: "3g", 
        timing: { cs: "S jídlem", en: "With food" }
    },
    { 
        id: 27, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/vitamin-d/", 
        icon: "☀️", 
        contains: ["Vitamín D3"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/21154341/", "https://pubmed.ncbi.nlm.nih.gov/21872433/"],
        synergy: ["Vitamín K2"], 
        conflict: [], 
        name: { cs: "Vitamín D3", en: "Vitamin D3" },
        description: { cs: "Hormonální vitamín. Zásadní pro imunitu.", en: "Hormonal vitamin. Crucial for immunity." },
        benefits: { cs: ["Imunita", "Kosti", "Nálada"], en: ["Immunity", "Bones", "Mood"] }, 
        dosage: "2000-5000 IU", 
        timing: { cs: "Ráno s tuky", en: "Morning with fats" }
    },
    { 
        id: 28, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/vitamin-k/", 
        icon: "🥦", 
        contains: ["Vitamín K2"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/23525168/", "https://pubmed.ncbi.nlm.nih.gov/15514282/"],
        synergy: ["Vitamín D3"], 
        conflict: [], 
        name: { cs: "Vitamín K2 (MK-7)", en: "Vitamin K2 (MK-7)" },
        description: { cs: "Směruje vápník do kostí místo do cév.", en: "Directs calcium to bones instead of arteries." },
        benefits: { cs: ["Zdravé cévy", "Kosti"], en: ["Healthy arteries", "Bones"] }, 
        dosage: "100mcg", 
        timing: { cs: "S jídlem", en: "With food" }
    },
    { 
        id: 29, 
        category: "Zdraví", 
        confidence: "medium", 
        link: "https://pubmed.ncbi.nlm.nih.gov/12470077/", 
        icon: "🥗", 
        contains: ["Vitamíny"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/12470077/", "https://pubmed.ncbi.nlm.nih.gov/23255561/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Multivitamín", en: "Multivitamin" },
        description: { cs: "Základní pojistka mikroživin.", en: "Basic micronutrient insurance." },
        benefits: { cs: ["Prevence deficitů"], en: ["Deficiency prevention"] }, 
        dosage: "1 dávka", 
        timing: { cs: "Ráno s jídlem", en: "Morning with food" }
    },
    { 
        id: 30, 
        category: "Zdraví", 
        confidence: "medium", 
        link: "https://examine.com/supplements/ashwagandha/", 
        icon: "🌿", 
        contains: ["Ashwagandha"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/23439798/", "https://pubmed.ncbi.nlm.nih.gov/31517876/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Ashwagandha (KSM-66)", en: "Ashwagandha (KSM-66)" },
        description: { cs: "Adaptogen snižující kortizol a stres.", en: "Adaptogen reducing cortisol and stress." },
        benefits: { cs: ["Méně stresu", "Spánek", "Testosteron"], en: ["Less stress", "Sleep", "Testosterone"] }, 
        dosage: "300-600mg", 
        timing: { cs: "Večer", en: "Evening" }
    },
    { 
        id: 31, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/vitamin-c/", 
        icon: "🍊", 
        contains: ["Vitamín C"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/23440782/", "https://pubmed.ncbi.nlm.nih.gov/10796569/"],
        synergy: ["Kolagen"], 
        conflict: ["Po tréninku"], 
        name: { cs: "Vitamín C", en: "Vitamin C" },
        description: { cs: "Antioxidant nutný pro imunitu a kolagen.", en: "Antioxidant needed for immunity and collagen." },
        benefits: { cs: ["Imunita", "Zdraví kůže"], en: ["Immunity", "Skin health"] }, 
        dosage: "500-1000mg", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 32, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/collagen/", 
        icon: "🦴", 
        contains: ["Kolagen"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/30681787/", "https://pubmed.ncbi.nlm.nih.gov/26362110/"],
        synergy: ["Vitamín C"], 
        conflict: [], 
        name: { cs: "Kolagen (Hydrolyzovaný)", en: "Collagen (Hydrolyzed)" },
        description: { cs: "Strukturální protein pro klouby a kůži.", en: "Structural protein for joints and skin." },
        benefits: { cs: ["Klouby", "Vlasy", "Kůže"], en: ["Joints", "Hair", "Skin"] }, 
        dosage: "10-20g", 
        timing: { cs: "Kdykoliv", en: "Anytime" }
    },
    { 
        id: 33, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/n-acetylcysteine/", 
        icon: "🧹", 
        contains: ["NAC"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/24080160/", "https://pubmed.ncbi.nlm.nih.gov/25653169/"],
        synergy: ["Glycin"], 
        conflict: ["Alkohol"], 
        name: { cs: "NAC", en: "NAC" },
        description: { cs: "Silný antioxidant, prekurzor glutathionu.", en: "Strong antioxidant, glutathione precursor." },
        benefits: { cs: ["Játra", "Dýchání"], en: ["Liver", "Respiratory"] }, 
        dosage: "600mg", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 34, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/curcumin/", 
        icon: "🍛", 
        contains: ["Kurkumin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22407144/", "https://pubmed.ncbi.nlm.nih.gov/29056187/"],
        synergy: ["Piperin"], 
        conflict: [], 
        name: { cs: "Kurkumin", en: "Curcumin" },
        description: { cs: "Silný protizánětlivý extrakt z kurkumy.", en: "Potent anti-inflammatory extract from turmeric." },
        benefits: { cs: ["Klouby", "Zánětlivost"], en: ["Joints", "Inflammation"] }, 
        dosage: "500mg", 
        timing: { cs: "S jídlem", en: "With food" }
    },
    { 
        id: 35, 
        category: "Zdraví", 
        confidence: "medium", 
        link: "https://examine.com/supplements/probiotics/", 
        icon: "🦠", 
        contains: ["Probiotika"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/28221993/", "https://pubmed.ncbi.nlm.nih.gov/25441326/"],
        synergy: ["Vláknina"], 
        conflict: ["Antibiotika"], 
        name: { cs: "Probiotika", en: "Probiotics" },
        description: { cs: "Živé kultury pro zdraví střev.", en: "Live cultures for gut health." },
        benefits: { cs: ["Trávení", "Imunita"], en: ["Digestion", "Immunity"] }, 
        dosage: "Dle produktu", 
        timing: { cs: "Ráno na lačno", en: "Morning empty stomach" }
    },
    { 
        id: 36, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://pubmed.ncbi.nlm.nih.gov/16763894/", 
        icon: "⚡", 
        contains: ["Vitamín B"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/16763894/", "https://pubmed.ncbi.nlm.nih.gov/21621531/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Vitamín B-Complex", en: "Vitamin B-Complex" },
        description: { cs: "Skupina vitamínů pro metabolismus energie.", en: "Group of vitamins for energy metabolism." },
        benefits: { cs: ["Energie", "Nervy"], en: ["Energy", "Nerves"] }, 
        dosage: "1 tbl", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 37, 
        category: "Zdraví", 
        confidence: "medium", 
        link: "https://examine.com/supplements/boron/", 
        icon: "🪨", 
        contains: ["Bór"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/21129941/", "https://pubmed.ncbi.nlm.nih.gov/11234857/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Boron (Bór)", en: "Boron" },
        description: { cs: "Stopový prvek, může zvyšovat volný testosteron.", en: "Trace mineral, may increase free testosterone." },
        benefits: { cs: ["Volný testosteron", "Kosti"], en: ["Free testosterone", "Bones"] }, 
        dosage: "3-9mg", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 38, 
        category: "Zdraví", 
        confidence: "medium", 
        link: "https://examine.com/supplements/tongkat-ali/", 
        icon: "🪵", 
        contains: ["Tongkat Ali"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/23754792/", "https://pubmed.ncbi.nlm.nih.gov/23240030/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Tongkat Ali", en: "Tongkat Ali" },
        description: { cs: "Bylina podporující mužské libido a hormony.", en: "Herb supporting male libido and hormones." },
        benefits: { cs: ["Libido", "Testosteron"], en: ["Libido", "Testosterone"] }, 
        dosage: "200-400mg", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 39, 
        category: "Zdraví", 
        confidence: "medium", 
        link: "https://examine.com/supplements/maca/", 
        icon: "🍠", 
        contains: ["Maca"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/12472620/", "https://pubmed.ncbi.nlm.nih.gov/18801111/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Maca Peruánská", en: "Maca Root" },
        description: { cs: "Kořen pro vitalitu a libido (neovlivňuje testosteron).", en: "Root for vitality and libido (does not affect testosterone)." },
        benefits: { cs: ["Libido", "Energie"], en: ["Libido", "Energy"] }, 
        dosage: "2-5g", 
        timing: { cs: "Ráno", en: "Morning" }
    },
    { 
        id: 40, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/coenzyme-q10/", 
        icon: "❤️", 
        contains: ["Q10"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/24461073/", "https://pubmed.ncbi.nlm.nih.gov/11997392/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Koenzym Q10", en: "Coenzyme Q10" },
        description: { cs: "Energie pro mitochondrie a zdraví srdce.", en: "Energy for mitochondria and heart health." },
        benefits: { cs: ["Srdce", "Energie"], en: ["Heart", "Energy"] }, 
        dosage: "100-200mg", 
        timing: { cs: "S jídlem", en: "With food" }
    },
    { 
        id: 49, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/glutamine/", 
        icon: "🛡️", 
        contains: ["Glutamin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/9178278/", "https://pubmed.ncbi.nlm.nih.gov/25445558/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Glutamin", en: "Glutamine" },
        description: { cs: "Palivo pro imunitu a střevní buňky.", en: "Fuel for immunity and gut cells." },
        benefits: { cs: ["Imunita", "Střeva"], en: ["Immunity", "Gut health"] }, 
        dosage: "5g", 
        timing: { cs: "Po tréninku / Večer", en: "Post-workout / Evening" }
    },
    { 
        id: 50, 
        category: "Zdraví", 
        confidence: "high", 
        link: "https://examine.com/supplements/psyllium/", 
        icon: "🌾", 
        contains: ["Vláknina"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/19445821/", "https://pubmed.ncbi.nlm.nih.gov/20696559/"],
        synergy: ["Probiotika"], 
        conflict: ["Léky"], 
        name: { cs: "Psyllium", en: "Psyllium Husk" },
        description: { cs: "Rozpustná vláknina pro zdravé trávení.", en: "Soluble fiber for healthy digestion." },
        benefits: { cs: ["Trávení", "Cholesterol"], en: ["Digestion", "Cholesterol"] }, 
        dosage: "5g", 
        timing: { cs: "Ráno / Večer", en: "Morning / Evening" }
    },

    // --- KATEGORIE: SPÁNEK (SLEEP) ---
    { 
        id: 41, 
        category: "Spánek", 
        confidence: "high", 
        link: "https://examine.com/supplements/melatonin/", 
        icon: "🌙", 
        contains: ["Melatonin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/23691095/", "https://pubmed.ncbi.nlm.nih.gov/28445426/"],
        synergy: [], 
        conflict: ["Kofein"], 
        name: { cs: "Melatonin", en: "Melatonin" },
        description: { cs: "Hormon tmy. Signalizuje tělu čas spát.", en: "Hormone of darkness. Signals sleep time." },
        benefits: { cs: ["Rychlé usnutí"], en: ["Fast sleep onset"] }, 
        dosage: "0.5-3mg", 
        timing: { cs: "30 min před spaním", en: "30 min before bed" }
    },
    { 
        id: 42, 
        category: "Spánek", 
        confidence: "high", 
        link: "https://examine.com/supplements/glycine/", 
        icon: "🍚", 
        contains: ["Glycin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22293292/", "https://pubmed.ncbi.nlm.nih.gov/17435133/"],
        synergy: ["NAC"], 
        conflict: [], 
        name: { cs: "Glycin", en: "Glycine" },
        description: { cs: "Zklidňuje mozek a snižuje tělesnou teplotu.", en: "Calms the brain and lowers body temp." },
        benefits: { cs: ["Hluboký spánek"], en: ["Deep sleep"] }, 
        dosage: "3g", 
        timing: { cs: "Před spaním", en: "Before bed" }
    },
    { 
        id: 43, 
        category: "Spánek", 
        confidence: "medium", 
        link: "https://examine.com/supplements/lemon-balm/", 
        icon: "🍃", 
        contains: ["Meduňka"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/20436515/", "https://pubmed.ncbi.nlm.nih.gov/21808006/"],
        synergy: ["Valeriána"], 
        conflict: [], 
        name: { cs: "Meduňka lékařská", en: "Lemon Balm" },
        description: { cs: "Bylina pro uklidnění a relaxaci.", en: "Herb for calming and relaxation." },
        benefits: { cs: ["Proti stresu"], en: ["Anti-stress"] }, 
        dosage: "300-600mg", 
        timing: { cs: "Večer", en: "Evening" }
    },
    { 
        id: 44, 
        category: "Spánek", 
        confidence: "medium", 
        link: "https://examine.com/supplements/valerian/", 
        icon: "🌿", 
        contains: ["Valeriána"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/16767761/", "https://pubmed.ncbi.nlm.nih.gov/20347389/"],
        synergy: ["Meduňka"], 
        conflict: [], 
        name: { cs: "Valeriána (Kozlík)", en: "Valerian Root" },
        description: { cs: "Silná bylina pro sedaci a spánek.", en: "Potent herb for sedation and sleep." },
        benefits: { cs: ["Usínání"], en: ["Sleep onset"] }, 
        dosage: "300-500mg", 
        timing: { cs: "Před spaním", en: "Before bed" }
    },
    { 
        id: 45, 
        category: "Spánek", 
        confidence: "medium", 
        link: "https://examine.com/supplements/gaba/", 
        icon: "🧘‍♂️", 
        contains: ["GABA"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/16971751/", "https://pubmed.ncbi.nlm.nih.gov/17127471/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "GABA", en: "GABA" },
        description: { cs: "Neurotransmiter pro relaxaci.", en: "Neurotransmitter for relaxation." },
        benefits: { cs: ["Uvolnění"], en: ["Relaxation"] }, 
        dosage: "500-1000mg", 
        timing: { cs: "Večer", en: "Evening" }
    },
    { 
        id: 46, 
        category: "Spánek", 
        confidence: "high", 
        link: "https://examine.com/supplements/tryptophan/", 
        icon: "🦃", 
        contains: ["Tryptofan"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/15147425/", "https://pubmed.ncbi.nlm.nih.gov/20569483/"],
        synergy: [], 
        conflict: ["SSRI"], 
        name: { cs: "L-Tryptofan", en: "L-Tryptophan" },
        description: { cs: "Prekurzor serotoninu a melatoninu.", en: "Precursor to serotonin and melatonin." },
        benefits: { cs: ["Nálada", "Spánek"], en: ["Mood", "Sleep"] }, 
        dosage: "500-1000mg", 
        timing: { cs: "Večer", en: "Evening" }
    },
    { 
        id: 47, 
        category: "Spánek", 
        confidence: "medium", 
        link: "https://examine.com/supplements/apigenin/", 
        icon: "🌼", 
        contains: ["Apigenin"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/20347389/", "https://pubmed.ncbi.nlm.nih.gov/25556272/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Apigenin", en: "Apigenin" },
        description: { cs: "Bioflavonoid z heřmánku. Uklidňuje mysl.", en: "Bioflavonoid from chamomile. Calms the mind." },
        benefits: { cs: ["Usínání"], en: ["Sleep onset"] }, 
        dosage: "50mg", 
        timing: { cs: "Večer", en: "Evening" }
    },
    { 
        id: 48, 
        category: "Spánek", 
        confidence: "high", 
        link: "https://examine.com/supplements/tart-cherry/", 
        icon: "🍒", 
        contains: ["Melatonin", "Antioxidanty"], 
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22038497/", "https://pubmed.ncbi.nlm.nih.gov/20459662/"],
        synergy: [], 
        conflict: [], 
        name: { cs: "Tart Cherry (Višeň)", en: "Tart Cherry" },
        description: { cs: "Přírodní zdroj melatoninu. Podporuje regeneraci.", en: "Natural source of melatonin. Supports recovery." },
        benefits: { cs: ["Spánek", "Regenerace"], en: ["Sleep", "Recovery"] }, 
        dosage: "Dle produktu", 
        timing: { cs: "Večer", en: "Evening" }
    },

    // --- V3 NEW SUPPLEMENTS ---
    {
        id: 51,
        category: "Zdraví",
        confidence: "high",
        link: "https://examine.com/supplements/astaxanthin/",
        icon: "🦀",
        contains: ["Astaxanthin"],
        studies: ["https://pubmed.ncbi.nlm.nih.gov/21197727/", "https://pubmed.ncbi.nlm.nih.gov/20637798/"],
        synergy: ["Omega-3"],
        conflict: [],
        name: { cs: "Astaxanthin", en: "Astaxanthin" },
        description: { cs: "Nejsilnější přírodní antioxidant. 6000× silnější než Vitamín C.", en: "Strongest natural antioxidant. 6000× more potent than Vitamin C." },
        benefits: { cs: ["Ochrana buněk", "Oční zdraví", "Pokožka"], en: ["Cell protection", "Eye health", "Skin"] },
        dosage: "4-12mg",
        timing: { cs: "S jídlem obsahujícím tuk", en: "With fatty meal" }
    },
    {
        id: 52,
        category: "Zdraví",
        confidence: "medium",
        link: "https://examine.com/supplements/berberine/",
        icon: "🌿",
        contains: ["Berberin"],
        studies: ["https://pubmed.ncbi.nlm.nih.gov/22116706/", "https://pubmed.ncbi.nlm.nih.gov/19800084/"],
        synergy: [],
        conflict: ["Léky na cukrovku"],
        name: { cs: "Berberin", en: "Berberine" },
        description: { cs: "Přírodní regulátor krevního cukru. Srovnatelný s Metforminem.", en: "Natural blood sugar regulator. Comparable to Metformin." },
        benefits: { cs: ["Glykémie", "Metabolismus", "Srdce"], en: ["Blood sugar", "Metabolism", "Heart"] },
        dosage: "500mg",
        timing: { cs: "Před jídlem", en: "Before meals" }
    },
    {
        id: 53,
        category: "Zdraví",
        confidence: "medium",
        link: "https://examine.com/supplements/nicotinamide-mononucleotide/",
        icon: "🔋",
        contains: ["NMN"],
        studies: ["https://pubmed.ncbi.nlm.nih.gov/26701494/", "https://pubmed.ncbi.nlm.nih.gov/24703712/"],
        synergy: ["Resveratrol"],
        conflict: [],
        name: { cs: "NMN (Nikotinamid Mononukleotid)", en: "NMN (Nicotinamide Mononucleotide)" },
        description: { cs: "Prekurzor NAD+. Podporuje buněčnou energii a dlouhověkost.", en: "NAD+ precursor. Supports cellular energy and longevity." },
        benefits: { cs: ["Buněčná energie", "Dlouhověkost", "DNA oprava"], en: ["Cellular energy", "Longevity", "DNA repair"] },
        dosage: "250-500mg",
        timing: { cs: "Ráno", en: "Morning" }
    },
    {
        id: 54,
        category: "Síla",
        confidence: "medium",
        link: "https://examine.com/supplements/fadogia-agrestis/",
        icon: "🌾",
        contains: ["Fadogia"],
        studies: ["https://pubmed.ncbi.nlm.nih.gov/16635908/", "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5278660/"],
        synergy: ["Tongkat Ali"],
        conflict: [],
        name: { cs: "Fadogia Agrestis", en: "Fadogia Agrestis" },
        description: { cs: "Africká bylina stimulující LH a hladiny testosteronu.", en: "African herb stimulating LH and testosterone levels." },
        benefits: { cs: ["Testosteron", "Libido", "Síla"], en: ["Testosterone", "Libido", "Strength"] },
        dosage: "400-600mg",
        timing: { cs: "Ráno (cyklovat 8–12 týdnů)", en: "Morning (cycle 8–12 weeks)" }
    },
    {
        id: 55,
        category: "Zdraví",
        confidence: "medium",
        link: "https://examine.com/supplements/shilajit/",
        icon: "🪨",
        contains: ["Fulvic acid", "Minerály"],
        studies: ["https://pubmed.ncbi.nlm.nih.gov/19755698/", "https://pubmed.ncbi.nlm.nih.gov/25771869/"],
        synergy: ["CoQ10"],
        conflict: [],
        name: { cs: "Shilajit", en: "Shilajit" },
        description: { cs: "Pryskyřice bohatá na fulvic acid a 85 minerálů.", en: "Resin rich in fulvic acid and 85 minerals." },
        benefits: { cs: ["Energie", "Testosteron", "Mitochondrie"], en: ["Energy", "Testosterone", "Mitochondria"] },
        dosage: "300-500mg",
        timing: { cs: "Ráno", en: "Morning" }
    },
    {
        id: 56,
        category: "Síla",
        confidence: "medium",
        link: "https://examine.com/supplements/turkesterone/",
        icon: "🏆",
        contains: ["Turkesteron"],
        studies: ["https://pubmed.ncbi.nlm.nih.gov/10997377/", "https://pubmed.ncbi.nlm.nih.gov/6538498/"],
        synergy: ["Kreatin"],
        conflict: [],
        name: { cs: "Turkesteron", en: "Turkesterone" },
        description: { cs: "Rostlinný ecdysteroid podporující proteosyntézu.", en: "Plant-based ecdysteroid supporting protein synthesis." },
        benefits: { cs: ["Svalová hmota", "Regenerace", "Síla"], en: ["Muscle mass", "Recovery", "Strength"] },
        dosage: "500mg",
        timing: { cs: "S jídlem", en: "With food" }
    },

    // --- V4.2.3 NEW SUPPLEMENTS ---
    {
        id: 57,
        category: "Zdraví",
        confidence: "low",
        link: "https://examine.com/supplements/tribulus-terrestris/",
        icon: "🌿",
        contains: ["Tribulus Terrestris", "Protodioscin"],
        studies: ["https://pubmed.ncbi.nlm.nih.gov/24559105/", "https://pubmed.ncbi.nlm.nih.gov/29172782/"],
        synergy: ["Maca", "Zinek", "Tongkat Ali"],
        conflict: ["Léky na cukrovku", "Léky na tlak"],
        name: { cs: "Tribulus Terrestris", en: "Tribulus Terrestris" },
        description: { cs: "Tradiční bylina pro libido. U zdravých mužů nemá spolehlivý vliv na testosteron.", en: "Traditional libido herb. It has not reliably increased testosterone in healthy men." },
        benefits: { cs: ["Libido", "Sexuální vitalita", "Možná podpora nálady"], en: ["Libido", "Sexual vitality", "Possible mood support"] },
        dosage: "500-1500mg",
        timing: { cs: "Ráno / s jídlem", en: "Morning / with food" }
    }
];

window.supplements = supplements;
